FROM postgres:13

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    postgresql-server-dev-all \
    libboost-all-dev \
    libeigen3-dev \
    libtiff5-dev \
    libpng-dev \
    libjpeg-dev \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    git


RUN git clone https://github.com/rdkit/rdkit.git
RUN cd rdkit && \
    python3 -m venv .venv && \
    . .venv/bin/activate && \
    python3 -m pip install numpy && \
    mkdir build && \
    cmake -DRDK_BUILD_PGSQL=ON && \
    make && \
    make install

EXPOSE 5432

CMD ["postgres"]